# Generated by Django 6.0 on 2025-12-19 08:50

import app.activity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=app.activity.models.activity_photo_path)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
