# Generated by Django 4.2.22 on 2025-12-08 10:23

import app.activity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.activity.models.activity_photo_path),
        ),
    ]
