# Generated by Django 4.2.22 on 2025-11-13 14:56

import app.photo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roommodel_main_photo'),
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file_url',
        ),
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=app.photo.models.room_photo_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rooms.roommodel'),
        ),
    ]
