# Generated by Django 4.2.22 on 2025-12-15 13:45

import app.photo.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roommodel_main_photo'),
        ('photo', '0002_remove_photo_file_url_photo_file_alter_photo_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=app.photo.models.room_thumbnail_path, verbose_name='Miniature'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(help_text='Formats acceptés : JPG, PNG, WebP. Taille max : 5MB', upload_to=app.photo.models.room_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), app.photo.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rooms.roommodel'),
        ),
    ]
