# Generated by Django 6.0 on 2026-03-17 13:02

import app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Email invalide')]),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='first_name',
            field=models.CharField(max_length=100, validators=[app.validators.validate_alphanumeric_spaces]),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='last_name',
            field=models.CharField(max_length=100, validators=[app.validators.validate_alphanumeric_spaces]),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[app.validators.validate_phone_number]),
        ),
    ]
