# Generated by Django 4.2.22 on 2025-11-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=7)),
                ('available', models.BooleanField(default=True)),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='room_photos/')),
            ],
        ),
    ]
