# Generated by Django 6.0 on 2025-12-19 08:50

import app.rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=7)),
                ('available', models.BooleanField(default=True)),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to=app.rooms.models.room_main_photo_path)),
                ('amenities', models.ManyToManyField(blank=True, related_name='rooms', to='rooms.amenitymodel')),
            ],
        ),
    ]
