# Generated by Django 6.0 on 2026-03-17 13:02

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='capacity',
            field=models.IntegerField(validators=[app.validators.validate_capacity]),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[app.validators.validate_price]),
        ),
    ]
