# Generated by Django 4.2.22 on 2025-11-13 14:56

import app.rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_amenitymodel_roommodel_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.rooms.models.room_main_photo_path),
        ),
    ]
