# Generated by Django 4.2.22 on 2025-12-08 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
        ('reservationActivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationactivity',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='reservation.reservation'),
        ),
    ]
